services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: task_calendar_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./logs:/var/www/html/logs
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - task_calendar_network

  db:
    image: mysql:8.0
    container_name: task_calendar_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

      - LANG=C.UTF-8
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - task_calendar_network

  cron:
    build:
      context: .
      dockerfile: docker/cron/Dockerfile
    container_name: task_calendar_cron
    volumes:
      - .:/var/www/html
      - ./logs:/var/www/html/logs
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
      - web
    networks:
      - task_calendar_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: task_calendar_ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http web:80
    depends_on:
      - web
    networks:
      - task_calendar_network

  ngrok_setup:
    build:
      context: .
      dockerfile: docker/ngrok_setup/Dockerfile
    container_name: task_calendar_ngrok_setup
    depends_on:
      - web
      - ngrok
    networks:
      - task_calendar_network
    volumes:
      - .:/var/www/html

networks:
  task_calendar_network:

volumes:
  mysql_data: